using System.Collections.Generic;
using NUnit.Framework;
using UnityEngine.UIElements;

namespace Velvet.Tests
{
    /// <summary>
    /// The bookkeeping a gap, grid or divide container keeps on a child it writes to: which slots it holds,
    /// and which containers re-apply when the child's own classes change.
    /// </summary>
    [TestFixture]
    internal sealed class HeldSlotOwnershipTests
    {
        private sealed class CountingOwner : Manipulator, IChildClassWatcher
        {
            public int Reapplied { get; private set; }

            public void Reapply() => Reapplied++;

            protected override void RegisterCallbacksOnTarget()
            {
            }

            protected override void UnregisterCallbacksFromTarget()
            {
            }
        }

        [TestCase(true, false, 8f, "ordinary")]
        [TestCase(false, false, 2f, "ordinary")]
        [TestCase(true, true, 2f, "ordinary")]
        [TestCase(false, false, 2f, "last-safe")]
        [TestCase(false, false, 2f, "crossing")]
        [TestCase(true, false, 8f, "crossing")]
        [TestCase(false, false, 2f, "empty")]
        [TestCase(false, false, 8f, "reapply")]
        [TestCase(true, false, 2f, "lower-layer")]
        public void Given_OverlappingLayersBehindAHold_When_TheSlotIsHandedBack_Then_PriorityAndArrivalChooseTheRestoredValue(bool longhandFirst, bool importantLonghand, float restored, string boundary)
        {
            // Arrange
            var element = new VisualElement();
            var longhand = new ArbitraryStyle(ArbitraryProperty.MarginTop, 2f, LengthUnit.Pixel);
            var shorthand = new ArbitraryStyle(ArbitraryProperty.Margin, 8f, LengthUnit.Pixel);
            var priority = importantLonghand
                ? StyleLayerPriority.ImportantOf(StyleLayerPriority.Base)
                : StyleLayerPriority.Base;
            var historyConsistent = true;
            Dictionary<(ArbitraryProperty, long), long>? arrivals = null;
            object? map = null;
            System.Reflection.FieldInfo? counter = null;
            if (boundary != "ordinary")
            {
                StyleArbitraryValueResolver.Apply(element, new ArbitraryStyle(ArbitraryProperty.Width, 1f, LengthUnit.Pixel));
                StyleArbitraryValueResolver.Clear(element, ArbitraryProperty.Width);
                var table = typeof(StyleArbitraryValueResolver).GetField("s_layers",
                    System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!.GetValue(null)!;
                var mapArgs = new object[] { element, null! };
                table.GetType().GetMethod("TryGetValue")!.Invoke(table, mapArgs);
                map = mapArgs[1];
                arrivals = (Dictionary<(ArbitraryProperty, long), long>)map.GetType().GetField("_arrivals",
                    System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)!.GetValue(map)!;
                counter = map.GetType().GetField("_nextArrival",
                    System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)!;
                historyConsistent = arrivals.Count == 0;
                // Compress an empty map's unrelated Apply/Clear history. Every live arrival below is
                // generated by ordinary Apply; the seed does not cross a rebase or inject layer records.
                counter.SetValue(map, boundary switch
                {
                    "last-safe" => long.MaxValue - 2,
                    "empty" => long.MaxValue,
                    "lower-layer" => long.MaxValue - 4,
                    "reapply" => 0L,
                    _ => long.MaxValue - 1,
                });
            }
            if (longhandFirst)
            {
                StyleArbitraryValueResolver.Apply(element, longhand, priority);
                StyleArbitraryValueResolver.Apply(element, shorthand);
            }
            else
            {
                StyleArbitraryValueResolver.Apply(element, shorthand);
                StyleArbitraryValueResolver.Apply(element, longhand, priority);
            }
            if (boundary == "lower-layer")
            {
                var upper = StyleLayerPriority.ImportantOf(StyleLayerPriority.Base);
                StyleArbitraryValueResolver.Apply(element, new ArbitraryStyle(ArbitraryProperty.MarginTop, 4f, LengthUnit.Pixel), upper);
                var beforeClear = element.style.marginTop.value.value;
                StyleArbitraryValueResolver.Apply(element, longhand, priority);
                // Re-register the hidden base longhand so insertion order differs from arrival order.
                // An unrelated writer crosses the boundary while both base layers and the upper layer stay live.
                StyleArbitraryValueResolver.Apply(element, new ArbitraryStyle(ArbitraryProperty.Width, 5f, LengthUnit.Pixel));
                historyConsistent &= (beforeClear,
                    arrivals![(ArbitraryProperty.MarginTop, StyleLayerPriority.Base)],
                    arrivals[(ArbitraryProperty.Margin, StyleLayerPriority.Base)],
                    arrivals[(ArbitraryProperty.MarginTop, upper)],
                    arrivals[(ArbitraryProperty.Width, StyleLayerPriority.Base)]) == (4f, 3L, 1L, 2L, 4L);
                StyleArbitraryValueResolver.Clear(element, ArbitraryProperty.MarginTop, upper);
                historyConsistent &= (arrivals!.Count, arrivals.ContainsKey((ArbitraryProperty.MarginTop, upper)),
                    element.style.width.value.value) == (3, false, 5f);
            }
            else if (boundary == "reapply")
            {
                // Retain both ordinary arrivals while compressing unrelated Apply/Clear history up to MaxValue.
                counter!.SetValue(map, long.MaxValue);
                StyleArbitraryValueResolver.Apply(element, shorthand);
                historyConsistent &= (arrivals!.Count,
                    arrivals[(ArbitraryProperty.MarginTop, StyleLayerPriority.Base)],
                    arrivals[(ArbitraryProperty.Margin, StyleLayerPriority.Base)]) == (2, 2L, 3L);
            }
            else if (boundary != "ordinary")
            {
                var first = longhandFirst ? ArbitraryProperty.MarginTop : ArbitraryProperty.Margin;
                var second = longhandFirst ? ArbitraryProperty.Margin : ArbitraryProperty.MarginTop;
                var lastSafe = boundary == "last-safe";
                historyConsistent &= (arrivals!.Count, arrivals[(first, StyleLayerPriority.Base)],
                    arrivals[(second, StyleLayerPriority.Base)])
                    == (2, lastSafe ? long.MaxValue - 1 : 1L, lastSafe ? long.MaxValue : 2L);
            }
            var settled = element.style.marginTop.value.value;
            StyleArbitraryValueResolver.Hold(element, HeldSlot.MarginTop, new StyleLength(12f));
            var held = element.style.marginTop.value.value;

            // Act
            StyleArbitraryValueResolver.HandBack(element, HeldSlot.MarginTop);

            // Assert
            Assert.That((settled, held, element.style.marginTop.value.value, historyConsistent),
                Is.EqualTo((restored, 12f, restored, true)));
        }

        [Test]
        public void Given_AnElementHoldingOneSlot_When_AnotherSlotIsHandedBackIfHeld_Then_ThatSlotsInlineValueStays()
        {
            // Arrange — a value nothing here wrote is not the hold layer's to clear.
            var element = new VisualElement();
            StyleArbitraryValueResolver.Hold(element, HeldSlot.MarginLeft, new StyleLength(4f));
            element.style.marginRight = 5f;

            // Act
            StyleArbitraryValueResolver.HandBackIfHeld(element, HeldSlot.MarginRight);

            // Assert
            Assert.That(element.style.marginRight.value.value, Is.EqualTo(5f));
        }

        [Test]
        public void Given_AChildTwoContainersClaimInTurn_When_ItsClassesChange_Then_OnlyTheLaterOwnerReapplies()
        {
            // Arrange
            var owners = new Dictionary<VisualElement, Manipulator>();
            var child = new VisualElement();
            var first = new CountingOwner();
            var second = new CountingOwner();
            StyleChildOwnership.Claim(owners, child, first);
            StyleChildOwnership.Claim(owners, child, second);

            // Act
            StyleArbitraryValueResolver.NotifyClassesChanged(child);

            // Assert
            Assert.That((first.Reapplied, second.Reapplied), Is.EqualTo((0, 1)));
        }

        [Test]
        public void Given_AChildItsOwnerReleased_When_ItsClassesChange_Then_TheFormerOwnerDoesNotReapply()
        {
            // Arrange
            var owners = new Dictionary<VisualElement, Manipulator>();
            var child = new VisualElement();
            var owner = new CountingOwner();
            StyleChildOwnership.Claim(owners, child, owner);
            var released = StyleChildOwnership.TryRelease(owners, child, owner);

            // Act
            StyleArbitraryValueResolver.NotifyClassesChanged(child);

            // Assert — the release rides along, since a claim never dropped would leave the owner watching.
            Assert.That((released, owner.Reapplied), Is.EqualTo((true, 0)));
        }

        [Test]
        public void Given_AClaimedChild_When_AClassLeavesIt_Then_ItsOwnerReapplies()
        {
            // Arrange
            var owners = new Dictionary<VisualElement, Manipulator>();
            var child = new VisualElement();
            child.AddToClassList("mr-2");
            var owner = new CountingOwner();
            StyleChildOwnership.Claim(owners, child, owner);

            // Act
            StyleClassProjection.Remove(child, "mr-2", StyleLayerPriority.Base);

            // Assert
            Assert.That(owner.Reapplied, Is.EqualTo(1));
        }
    }
}
