using System.Collections.Generic;
using NUnit.Framework;
using UnityEngine.UIElements;

namespace Velvet.Tests
{
    /// <summary>
    /// The bookkeeping a gap, grid or divide container keeps on a child it writes to: which slots it holds,
    /// and which containers re-apply when the child's own classes change.
    /// </summary>
    [TestFixture]
    internal sealed class HeldSlotOwnershipTests
    {
        private sealed class CountingOwner : Manipulator, IChildClassWatcher
        {
            public int Reapplied { get; private set; }

            public void Reapply() => Reapplied++;

            protected override void RegisterCallbacksOnTarget()
            {
            }

            protected override void UnregisterCallbacksFromTarget()
            {
            }
        }

        [TestCase(true, false, 8f, false)]
        [TestCase(false, false, 2f, false)]
        [TestCase(true, true, 2f, false)]
        [TestCase(true, false, 8f, true)]
        public void Given_OverlappingLayersBehindAHold_When_TheSlotIsHandedBack_Then_PriorityAndArrivalChooseTheRestoredValue(bool longhandFirst, bool importantLonghand, float restored, bool counterCycle)
        {
            // Arrange
            var element = new VisualElement();
            var longhand = new ArbitraryStyle(ArbitraryProperty.MarginTop, 2f, LengthUnit.Pixel);
            var shorthand = new ArbitraryStyle(ArbitraryProperty.Margin, 8f, LengthUnit.Pixel);
            var priority = importantLonghand
                ? StyleLayerPriority.ImportantOf(StyleLayerPriority.Base)
                : StyleLayerPriority.Base;
            var historyConsistent = true;
            if (longhandFirst)
            {
                StyleArbitraryValueResolver.Apply(element, longhand, priority);
                if (counterCycle)
                {
                    // Compress unrelated Width Apply/Clear history through a full counter cycle while Top stays live:
                    // after 2^64-1 pairs the counter returns to zero; the next ordinary Apply records one.
                    // One pair below checks that Clear retains Top and removes Width; seed only the remaining
                    // counter history. Both compared arrivals are generated by ordinary Apply, never injected.
                    StyleArbitraryValueResolver.Apply(element, new ArbitraryStyle(ArbitraryProperty.Width, 1f, LengthUnit.Pixel));
                    StyleArbitraryValueResolver.Clear(element, ArbitraryProperty.Width);
                    var table = typeof(StyleArbitraryValueResolver).GetField("s_layers",
                        System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!.GetValue(null)!;
                    var mapArgs = new object[] { element, null! };
                    table.GetType().GetMethod("TryGetValue")!.Invoke(table, mapArgs);
                    var map = mapArgs[1];
                    var arrivals = (Dictionary<(ArbitraryProperty, long), long>)map.GetType().GetField("_arrivals",
                        System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)!.GetValue(map)!;
                    historyConsistent = arrivals.Count == 1 && arrivals[(ArbitraryProperty.MarginTop, priority)] == 1;
                    map.GetType().GetField("_nextArrival",
                        System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)!.SetValue(map, 0L);
                    StyleArbitraryValueResolver.Apply(element, shorthand);
                    historyConsistent &= arrivals.Count == 2
                        && arrivals[(ArbitraryProperty.MarginTop, priority)] == 1
                        && arrivals[(ArbitraryProperty.Margin, StyleLayerPriority.Base)] == 1;
                }
                else
                {
                    StyleArbitraryValueResolver.Apply(element, shorthand);
                }
            }
            else
            {
                StyleArbitraryValueResolver.Apply(element, shorthand);
                StyleArbitraryValueResolver.Apply(element, longhand, priority);
            }
            StyleArbitraryValueResolver.Hold(element, HeldSlot.MarginTop, new StyleLength(12f));
            var held = element.style.marginTop.value.value;

            // Act
            StyleArbitraryValueResolver.HandBack(element, HeldSlot.MarginTop);

            // Assert
            Assert.That((held, element.style.marginTop.value.value, historyConsistent), Is.EqualTo((12f, restored, true)));
        }

        [Test]
        public void Given_AnElementHoldingOneSlot_When_AnotherSlotIsHandedBackIfHeld_Then_ThatSlotsInlineValueStays()
        {
            // Arrange — a value nothing here wrote is not the hold layer's to clear.
            var element = new VisualElement();
            StyleArbitraryValueResolver.Hold(element, HeldSlot.MarginLeft, new StyleLength(4f));
            element.style.marginRight = 5f;

            // Act
            StyleArbitraryValueResolver.HandBackIfHeld(element, HeldSlot.MarginRight);

            // Assert
            Assert.That(element.style.marginRight.value.value, Is.EqualTo(5f));
        }

        [Test]
        public void Given_AChildTwoContainersClaimInTurn_When_ItsClassesChange_Then_OnlyTheLaterOwnerReapplies()
        {
            // Arrange
            var owners = new Dictionary<VisualElement, Manipulator>();
            var child = new VisualElement();
            var first = new CountingOwner();
            var second = new CountingOwner();
            StyleChildOwnership.Claim(owners, child, first);
            StyleChildOwnership.Claim(owners, child, second);

            // Act
            StyleArbitraryValueResolver.NotifyClassesChanged(child);

            // Assert
            Assert.That((first.Reapplied, second.Reapplied), Is.EqualTo((0, 1)));
        }

        [Test]
        public void Given_AChildItsOwnerReleased_When_ItsClassesChange_Then_TheFormerOwnerDoesNotReapply()
        {
            // Arrange
            var owners = new Dictionary<VisualElement, Manipulator>();
            var child = new VisualElement();
            var owner = new CountingOwner();
            StyleChildOwnership.Claim(owners, child, owner);
            var released = StyleChildOwnership.TryRelease(owners, child, owner);

            // Act
            StyleArbitraryValueResolver.NotifyClassesChanged(child);

            // Assert — the release rides along, since a claim never dropped would leave the owner watching.
            Assert.That((released, owner.Reapplied), Is.EqualTo((true, 0)));
        }

        [Test]
        public void Given_AClaimedChild_When_AClassLeavesIt_Then_ItsOwnerReapplies()
        {
            // Arrange
            var owners = new Dictionary<VisualElement, Manipulator>();
            var child = new VisualElement();
            child.AddToClassList("mr-2");
            var owner = new CountingOwner();
            StyleChildOwnership.Claim(owners, child, owner);

            // Act
            StyleClassProjection.Remove(child, "mr-2", StyleLayerPriority.Base);

            // Assert
            Assert.That(owner.Reapplied, Is.EqualTo(1));
        }
    }
}
