using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Velvet.Tests.Component.Editor")]
[assembly: InternalsVisibleTo("Velvet.Tests.Component.PlayMode")]
[assembly: InternalsVisibleTo("Velvet.Tests.Hooks.Editor")]
[assembly: InternalsVisibleTo("Velvet.Tests.Hooks.PlayMode")]
[assembly: InternalsVisibleTo("Velvet.Tests.Reconciler.Editor")]
[assembly: InternalsVisibleTo("Velvet.Tests.Reconciler.PlayMode")]
[assembly: InternalsVisibleTo("Velvet.Tests.Routing.Editor")]
[assembly: InternalsVisibleTo("Velvet.Tests.Store.Editor")]
[assembly: InternalsVisibleTo("Velvet.Tests.Store.PlayMode")]
[assembly: InternalsVisibleTo("Velvet.Tests.Styling.Editor")]
[assembly: InternalsVisibleTo("Velvet.TestUtilities")]
[assembly: InternalsVisibleTo("Velvet.Editor")]
[assembly: InternalsVisibleTo("Unity.Velvet.CodeGen")]
