// <auto-generated/>
#nullable disable

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode BuildHeader(string title)
            => global::Velvet.V.Memoized(() => BuildHeader_Impl(title), title);
    }
}
