// <auto-generated/>
#nullable disable

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode Build(int a, int b, int c, int d, int e, int f, int g, int h)
            => global::Velvet.V.Memoized(() => Build_Impl(a, b, c, d, e, f, g, h), a, b, c, d, e, f, g, h);
    }
}
