// <auto-generated/>
#nullable disable

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode BuildHeader(string title)
            => global::Velvet.V.Memoized(() => BuildHeader_Impl(title), title);

        private partial global::Velvet.VNode BuildFooter(int count)
            => global::Velvet.V.Memoized(() => BuildFooter_Impl(count), count);
    }
}
