#!/usr/bin/env python3
"""Generate client configuration from the repository harness; --check never writes."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EVENTS = {name: name[0].lower() + name[1:] for name in
          ("SessionStart", "SubagentStop", "PreToolUse", "PostToolUse", "Stop")}


LINKS = {
    ".claude/hooks": "../.harness/hooks",
    ".codex/hooks": "../.harness/hooks",
    ".claude/skills": "../.agents/skills",
    ".claude/agents": "../.harness/agents",
}


def outputs(root):
    source = root / ".harness"
    result = {"CLAUDE.md": "<!-- Generated by scripts/harness/sync.py. -->\n@AGENTS.md\n"}
    for path in (source / "agents").glob("*.md"):
        text = path.read_text()
        _, header, body = text.split("---", 2)
        fields = dict(line.split(": ", 1) for line in header.splitlines() if ": " in line)
        reference = f"Read and follow `.harness/agents/{path.name}` before starting work. The Markdown body defines this role."
        result[f".cursor/agents/{path.name}"] = (
            f"---\nname: {fields['name']}\ndescription: {fields['description']}\n---\n\n<!-- Generated by scripts/harness/sync.py. -->\n" + reference + "\n")
        result[f".codex/agents/{path.stem}.toml"] = (
            "# Generated by scripts/harness/sync.py.\n"
            + "\n".join(f"{key} = {json.dumps(value, ensure_ascii=False)}" for key, value in
                        (("name", fields["name"]), ("description", fields["description"]),
                         ("developer_instructions", reference))) + "\n")
    manifest = json.loads((source / "hooks.json").read_text())
    for client in ("claude", "codex", "cursor"):
        hooks = {}
        for entry in manifest:
            event, names = entry["event"], entry["tools"]
            if client == "claude":
                command = 'python3 "$CLAUDE_PROJECT_DIR/.claude/hooks/' + entry["script"] + '"'
            else:
                command = ('python3 "$(git rev-parse --show-toplevel)/scripts/harness/adapter.py" '
                           + f'{client} {event} {entry["script"]}')
            definition = {"command": command, "timeout": entry["timeout"]}
            if client == "cursor":
                if names:
                    definition["matcher"] = "|".join("Shell" if n == "Bash" else n for n in names)
                if event == "PreToolUse":
                    definition["failClosed"] = True
                hooks.setdefault(EVENTS[event], []).append(definition)
            else:
                definition["type"] = "command"
                group = {"hooks": [definition]}
                if names:
                    group["matcher"] = "|".join(names)
                hooks.setdefault(event, []).append(group)
        config = {"hooks": hooks}
        if client == "cursor":
            config["version"] = 1
        destination = f".{client}/" + ("settings.json" if client == "claude" else "hooks.json")
        if client == "claude":
            existing = json.loads((root / destination).read_text())
            config = {**existing, **config}
        result[destination] = json.dumps(config, indent=2) + "\n"
    return result


def synchronize(root, check=False):
    changed = []
    generated = outputs(root)
    for relative, target in LINKS.items():
        path = root / relative
        if path.is_symlink() and path.readlink().as_posix() == target:
            continue
        if path.exists() or path.is_symlink():
            raise ValueError(f"Expected shared-source symlink; preserve and migrate existing path: {relative}")
        changed.append(relative)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.symlink_to(target, target_is_directory=True)
    for directory, pattern in ((".codex/agents", "*.toml"), (".cursor/agents", "*.md")):
        for path in (root / directory).glob(pattern):
            relative = path.relative_to(root).as_posix()
            if relative not in generated and "Generated by scripts/harness/sync.py." in path.read_text():
                changed.append(relative)
                if not check:
                    path.unlink()
    for relative, content in generated.items():
        path = root / relative
        if not path.exists() or path.read_text() != content:
            changed.append(relative)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
    return changed


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = synchronize(ROOT, args.check)
    if changed:
        print(("Out of date:\n" if args.check else "Generated:\n") + "\n".join(changed))
    return int(args.check and bool(changed))


if __name__ == "__main__":
    raise SystemExit(main())
