        /// <summary>
        /// 2-argument generic memoization with key (auto-generated by Velvet.SourceGenerators).
        /// </summary>
        public static MemoNode MemoizedWithKey<T1, T2>(string key, Func<VNode> factory, T1 dep1, T2 dep2)
            where T1 : IEquatable<T1>
            where T2 : IEquatable<T2>
        {
            return new MemoNode
            {
                Key = key,
                Factory = factory,
                Dependencies = new object[] { dep1, dep2 },
            };
        }
