        /// <summary>
        /// 5-argument generic memoization (auto-generated by Velvet.SourceGenerators).
        /// The IEquatable&lt;T&gt; constraint guarantees type-safe dependency comparison.
        /// </summary>
        public static MemoNode Memoized<T1, T2, T3, T4, T5>(Func<VNode> factory, T1 dep1, T2 dep2, T3 dep3, T4 dep4, T5 dep5)
            where T1 : IEquatable<T1>
            where T2 : IEquatable<T2>
            where T3 : IEquatable<T3>
            where T4 : IEquatable<T4>
            where T5 : IEquatable<T5>
        {
            return new MemoNode
            {
                Factory = factory,
                Dependencies = new object[] { dep1, dep2, dep3, dep4, dep5 },
            };
        }
