using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;
using Velvet.SourceGenerators.Shared;

namespace Velvet.SourceGenerators
{
    /// <summary>
    /// Incremental Source Generator that auto-generates fixed-arity overloads (T1..T8) for V.Memoized and
    /// V.MemoizedWithKey. Calls with 9+ arguments fall back to the existing params object[] overload.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class MemoOverloadGenerator : IIncrementalGenerator
    {
        internal const int MinArity = 1;
        internal const int MaxArity = 8;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // The analyzer DLL is applied (via the RoslynAnalyzer label) to every asmdef that references Velvet,
            // but V.Memoized<T1..T8> is intended to extend the partial class V inside the Velvet assembly only.
            // Generating a same-named V partial in other asmdefs would shadow Velvet.V's methods (Div / Label, etc.),
            // so we restrict the target to the Velvet assembly itself by assembly name.
            var shouldEmit = context.CompilationProvider.Select(static (compilation, _) =>
                compilation.AssemblyName == "Velvet");

            context.RegisterSourceOutput(shouldEmit, static (spc, emit) =>
            {
                if (!emit)
                {
                    return;
                }
                var source = GenerateOverloads();
                spc.AddSource("V.Memoized.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }

        internal static string GenerateOverloads()
        {
            var sb = new SourceBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace Velvet");
            using (sb.Block())
            {
                sb.AppendLine("public static partial class V");
                using (sb.Block())
                {
                    for (var arity = MinArity; arity <= MaxArity; arity++)
                    {
                        AppendMemoOverload(sb, arity);
                        sb.AppendLine();
                        AppendMemoWithKeyOverload(sb, arity);
                        if (arity < MaxArity)
                        {
                            sb.AppendLine();
                        }
                    }
                }
            }
            return sb.ToString();
        }

        private static void AppendMemoOverload(SourceBuilder sb, int arity)
        {
            var typeParams = TypeParamList(arity);
            var paramList = "Func<VNode> factory, " + DepParamList(arity);
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {arity}-argument generic memoization (auto-generated by Velvet.SourceGenerators).");
            sb.AppendLine("/// The IEquatable&lt;T&gt; constraint guarantees type-safe dependency comparison.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"public static MemoNode Memoized<{typeParams}>({paramList})");
            AppendWhereClauses(sb, arity);
            using (sb.Block())
            {
                sb.AppendLine("return new MemoNode");
                sb.AppendLine("{");
                sb.AppendLine($"    Factory = factory,");
                sb.AppendLine($"    Dependencies = new object[] {{ {DepArgList(arity)} }},");
                sb.AppendLine("};");
            }
        }

        private static void AppendMemoWithKeyOverload(SourceBuilder sb, int arity)
        {
            var typeParams = TypeParamList(arity);
            var paramList = "string key, Func<VNode> factory, " + DepParamList(arity);
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// {arity}-argument generic memoization with key (auto-generated by Velvet.SourceGenerators).");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"public static MemoNode MemoizedWithKey<{typeParams}>({paramList})");
            AppendWhereClauses(sb, arity);
            using (sb.Block())
            {
                sb.AppendLine("return new MemoNode");
                sb.AppendLine("{");
                sb.AppendLine($"    Key = key,");
                sb.AppendLine($"    Factory = factory,");
                sb.AppendLine($"    Dependencies = new object[] {{ {DepArgList(arity)} }},");
                sb.AppendLine("};");
            }
        }

        private static void AppendWhereClauses(SourceBuilder sb, int arity)
        {
            for (var i = 1; i <= arity; i++)
            {
                sb.AppendLine($"    where T{i} : IEquatable<T{i}>");
            }
        }

        private static string TypeParamList(int arity) =>
            string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));

        private static string DepParamList(int arity) =>
            string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i} dep{i}"));

        private static string DepArgList(int arity) =>
            string.Join(", ", Enumerable.Range(1, arity).Select(i => $"dep{i}"));
    }
}
