        /// <summary>
        /// 1-argument generic memoization with key (auto-generated by Velvet.SourceGenerators).
        /// </summary>
        public static MemoNode MemoizedWithKey<T1>(string key, Func<VNode> factory, T1 dep1)
            where T1 : IEquatable<T1>
        {
            return new MemoNode
            {
                Key = key,
                Factory = factory,
                Dependencies = new object[] { dep1 },
            };
        }
