        /// <summary>
        /// 4-argument generic memoization with key (auto-generated by Velvet.SourceGenerators).
        /// </summary>
        public static MemoNode MemoizedWithKey<T1, T2, T3, T4>(string key, Func<VNode> factory, T1 dep1, T2 dep2, T3 dep3, T4 dep4)
            where T1 : IEquatable<T1>
            where T2 : IEquatable<T2>
            where T3 : IEquatable<T3>
            where T4 : IEquatable<T4>
        {
            return new MemoNode
            {
                Key = key,
                Factory = factory,
                Dependencies = new object[] { dep1, dep2, dep3, dep4 },
            };
        }
