        /// <summary>
        /// 2-argument generic memoization (auto-generated by Velvet.SourceGenerators).
        /// The IEquatable&lt;T&gt; constraint guarantees type-safe dependency comparison.
        /// </summary>
        public static MemoNode Memoized<T1, T2>(Func<VNode> factory, T1 dep1, T2 dep2)
            where T1 : IEquatable<T1>
            where T2 : IEquatable<T2>
        {
            return new MemoNode
            {
                Factory = factory,
                Dependencies = new object[] { dep1, dep2 },
            };
        }
