        /// <summary>
        /// 1-argument generic memoization (auto-generated by Velvet.SourceGenerators).
        /// The IEquatable&lt;T&gt; constraint guarantees type-safe dependency comparison.
        /// </summary>
        public static MemoNode Memoized<T1>(Func<VNode> factory, T1 dep1)
            where T1 : IEquatable<T1>
        {
            return new MemoNode
            {
                Factory = factory,
                Dependencies = new object[] { dep1 },
            };
        }
