using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Velvet.StyleTable
{
    /// <summary>
    /// Writes the utility class → property table, and the types it is expressed in, as C# source.
    /// </summary>
    /// <remarks>
    /// The fixed parts are verbatim templates rather than a sequence of append calls, so the emitted types
    /// read as the C# they are in this file. Only the three tables — the longhand enum, the distinct property
    /// sets and the class map — are built line by line, because only those vary.
    /// </remarks>
    internal static class StyleUtilityTableEmitter
    {
        private const string Header = @"// <auto-generated/>
//
// Derived from Runtime/Styles/*.uss by Generators~/src/Velvet.StyleTable. Regenerate with
// Generators~/build.sh (or build.ps1) after editing a stylesheet; edits made here are overwritten,
// and BundledStyleSheetCensusTests fails if this file no longer matches the stylesheets.
#nullable disable
using System;
using System.Collections.Generic;

namespace Velvet
{
    /// <summary>
    /// Every UI Toolkit style property with its own storage slot, which is the granularity two classes can
    /// contend for. Shorthands are absent: they are expanded into these when the table is built, so a
    /// comparison never has to reconcile two spellings of the same slot.
    /// </summary>
    internal enum StyleLonghand
    {
";

        private const string AfterLonghandEnum = @"    }

    /// <summary>
    /// The extra condition a utility's rule carries beyond its class being present. A gated rule's selector
    /// is one simple selector longer than a bare utility's, so it outranks every plain single-class rule and
    /// applies only while its gate holds; two utilities contend for a property only when they share a gate.
    /// </summary>
    internal enum StyleUtilityGate
    {
";

        private const string AfterGateEnum = @"    }

    /// <summary>A set of <see cref=""StyleLonghand""/> values, held as a fixed-width bit set.</summary>
    /// <remarks>
    /// The backing words are private so widening the set stays a change to this type alone. The derivation
    /// refuses to emit a vocabulary larger than <see cref=""Capacity""/> rather than let the properties past
    /// the limit fall out of every set and make the classes that write them look conflict-free.
    /// </remarks>
    internal readonly struct StyleLonghandSet : IEquatable<StyleLonghandSet>
    {
        /// <summary>How many distinct longhands a set can hold.</summary>
        public const int Capacity = {CAPACITY};

        private const int WordBits = 64;

        private readonly ulong _word0;
        private readonly ulong _word1;

        /// <summary>Builds a set from its packed form. The table below is its only caller.</summary>
        internal StyleLonghandSet(ulong word0, ulong word1)
        {
            _word0 = word0;
            _word1 = word1;
        }

        /// <summary>The set holding no property.</summary>
        public static StyleLonghandSet Empty => default;

        /// <summary>The set holding <paramref name=""longhand""/> alone.</summary>
        public static StyleLonghandSet Of(StyleLonghand longhand)
        {
            var index = (int)longhand;
            return index < WordBits
                ? new StyleLonghandSet(1UL << index, 0UL)
                : new StyleLonghandSet(0UL, 1UL << (index - WordBits));
        }

        public bool IsEmpty => (_word0 | _word1) == 0UL;

        public bool Contains(StyleLonghand longhand) => Overlaps(Of(longhand));

        /// <summary>Whether the two sets hold a property in common, which is what a conflict is.</summary>
        public bool Overlaps(StyleLonghandSet other) =>
            ((_word0 & other._word0) | (_word1 & other._word1)) != 0UL;

        public StyleLonghandSet Union(StyleLonghandSet other) =>
            new StyleLonghandSet(_word0 | other._word0, _word1 | other._word1);

        public bool Equals(StyleLonghandSet other) => _word0 == other._word0 && _word1 == other._word1;

        public override bool Equals(object obj) => obj is StyleLonghandSet other && Equals(other);

        public override int GetHashCode() => (_word0 ^ _word1).GetHashCode();

        public static bool operator ==(StyleLonghandSet left, StyleLonghandSet right) => left.Equals(right);

        public static bool operator !=(StyleLonghandSet left, StyleLonghandSet right) => !left.Equals(right);
    }

    /// <summary>What one bundled utility class sets, and under what condition it sets it.</summary>
    internal readonly struct StyleUtilityRule
    {
        internal StyleUtilityRule(StyleLonghandSet properties, StyleUtilityGate gate)
        {
            Properties = properties;
            Gate = gate;
        }

        public StyleLonghandSet Properties { get; }

        public StyleUtilityGate Gate { get; }
    }

    /// <summary>Which longhand properties each bundled utility class writes.</summary>
    /// <remarks>
    /// A class absent from the table carries no USS rule that names it. That is the normal state for the
    /// utility families Velvet implements in C# rather than in USS — their partials declare no rules at all
    /// and say so in their own headers — so an absent class means ""no USS payload"", never ""not a utility"".
    /// </remarks>
    internal static class StyleUtilityProperties
    {
        /// <summary>Size of the longhand vocabulary the property sets are indexed over.</summary>
        public const int LonghandCount = {LONGHAND_COUNT};

        // Utilities repeat property sets heavily (every colour utility writes background-color alone), so the
        // distinct sets are stored once and the class map holds indices into them.
        private static readonly StyleUtilityRule[] Rules =
        {
";

        private const string AfterRules = @"        };

        private static readonly Dictionary<string, int> ByClassName =
            new Dictionary<string, int>({ENTRY_COUNT}, StringComparer.Ordinal)
        {
";

        private const string AfterClassMap = @"        };

        /// <summary>How many bundled utility classes carry a USS rule.</summary>
        public static int Count => ByClassName.Count;

        /// <summary>The rule for <paramref name=""className""/>, if the bundled stylesheets define one.</summary>
        public static bool TryGet(string className, out StyleUtilityRule rule)
        {
            if (className != null && ByClassName.TryGetValue(className, out var index))
            {
                rule = Rules[index];
                return true;
            }
            rule = default;
            return false;
        }
    }

    /// <summary>
    /// The bundled utilities that declare <c>transition-property</c>, in cascade order, with the properties
    /// each one's value names. <c>MotionNativeTransitionGuard.DeclaredSlots</c> is the only consumer and
    /// states what the order means.
    /// </summary>
    /// <remarks>
    /// Only ungated rules reach here: the derivation refuses a gated <c>transition-property</c> rather than
    /// record one, since no reader working from a class list can tell whether the gate holds.
    /// </remarks>
    internal static class StyleTransitionUtilities
    {
        private static readonly StyleLonghandSet[] Declared =
        {
";

        private const string AfterTransitionSets = @"        };

        private static readonly Dictionary<string, int> ByClassName =
            new Dictionary<string, int>({TRANSITION_COUNT}, StringComparer.Ordinal)
        {
";

        private const string Footer = @"        };

        /// <summary>How many bundled utilities declare <c>transition-property</c>.</summary>
        public static int Count => ByClassName.Count;

        /// <summary>
        /// The cascade position of <paramref name=""className""/> among the utilities that declare
        /// <c>transition-property</c>, and the properties its declaration names.
        /// </summary>
        public static bool TryGet(string className, out int cascadePosition, out StyleLonghandSet properties)
        {
            if (className != null && ByClassName.TryGetValue(className, out cascadePosition))
            {
                properties = Declared[cascadePosition];
                return true;
            }
            cascadePosition = -1;
            properties = StyleLonghandSet.Empty;
            return false;
        }
    }
}
";

        public static string Emit(StyleUtilityTable table)
        {
            var rules = new List<StyleUtilityTableEntry>();
            var ruleOfEntry = new List<int>(table.Entries.Length);
            IndexDistinctRules(table, rules, ruleOfEntry);

            var sb = new StringBuilder();
            sb.Append(Header);
            AppendLonghandEnum(sb, table);
            sb.Append(AfterLonghandEnum);
            AppendGateEnum(sb);
            sb.Append(AfterGateEnum
                .Replace("{CAPACITY}", Number(StyleUtilityTableBuilder.PropertySetCapacity))
                .Replace("{LONGHAND_COUNT}", Number(table.Longhands.Length)));
            AppendRules(sb, rules);
            sb.Append(AfterRules.Replace("{ENTRY_COUNT}", Number(table.Entries.Length)));
            AppendClassMap(sb, table, ruleOfEntry);
            sb.Append(AfterClassMap);
            AppendTransitionSets(sb, table);
            sb.Append(AfterTransitionSets.Replace("{TRANSITION_COUNT}", Number(table.Transitions.Length)));
            AppendTransitionClassMap(sb, table);
            sb.Append(Footer);
            return sb.ToString();
        }

        private static void AppendTransitionSets(StringBuilder sb, StyleUtilityTable table)
        {
            foreach (var transition in table.Transitions)
            {
                sb.Append("            new StyleLonghandSet(0x")
                    .Append(transition.Word0.ToString("X16", CultureInfo.InvariantCulture))
                    .Append("UL, 0x")
                    .Append(transition.Word1.ToString("X16", CultureInfo.InvariantCulture))
                    .Append("UL),\n");
            }
        }

        private static void AppendTransitionClassMap(StringBuilder sb, StyleUtilityTable table)
        {
            for (var i = 0; i < table.Transitions.Length; i++)
            {
                sb.Append("            { \"")
                    .Append(table.Transitions[i].ClassName)
                    .Append("\", ")
                    .Append(Number(i))
                    .Append(" },\n");
            }
        }

        /// <summary>
        /// Collapses the property sets to their distinct values, in order of first use so the numbering is a
        /// function of the stylesheets alone.
        /// </summary>
        private static void IndexDistinctRules(
            StyleUtilityTable table, List<StyleUtilityTableEntry> rules, List<int> ruleOfEntry)
        {
            var seen = new Dictionary<(ulong, ulong, UssGate), int>();
            foreach (var entry in table.Entries)
            {
                var key = (entry.Word0, entry.Word1, entry.Gate);
                if (!seen.TryGetValue(key, out var index))
                {
                    index = rules.Count;
                    seen.Add(key, index);
                    rules.Add(entry);
                }
                ruleOfEntry.Add(index);
            }
        }

        private static void AppendLonghandEnum(StringBuilder sb, StyleUtilityTable table)
        {
            for (var i = 0; i < table.Longhands.Length; i++)
            {
                var longhand = table.Longhands[i];
                sb.Append("        /// <summary>The USS <c>").Append(longhand.UssName).Append("</c> property.</summary>\n");
                sb.Append("        ").Append(longhand.Identifier).Append(" = ").Append(Number(i)).Append(",\n");
            }
        }

        private static void AppendGateEnum(StringBuilder sb)
        {
            foreach (UssGate gate in Enum.GetValues(typeof(UssGate)))
            {
                sb.Append("        ").Append(gate).Append(" = ").Append(Number((int)gate)).Append(",\n");
            }
        }

        private static void AppendRules(StringBuilder sb, List<StyleUtilityTableEntry> rules)
        {
            foreach (var rule in rules)
            {
                sb.Append("            new StyleUtilityRule(new StyleLonghandSet(0x")
                    .Append(rule.Word0.ToString("X16", CultureInfo.InvariantCulture))
                    .Append("UL, 0x")
                    .Append(rule.Word1.ToString("X16", CultureInfo.InvariantCulture))
                    .Append("UL), StyleUtilityGate.")
                    .Append(rule.Gate)
                    .Append("),\n");
            }
        }

        private static void AppendClassMap(StringBuilder sb, StyleUtilityTable table, List<int> ruleOfEntry)
        {
            for (var i = 0; i < table.Entries.Length; i++)
            {
                sb.Append("            { \"")
                    .Append(table.Entries[i].ClassName)
                    .Append("\", ")
                    .Append(Number(ruleOfEntry[i]))
                    .Append(" },\n");
            }
        }

        private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);
    }
}
