// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode BuildHeader(string title, int count, bool visible)
            => global::Velvet.V.Memoized(() => BuildHeader_Impl(title, count, visible), new object?[] { title, count, visible });
    }
}
