// <auto-generated/>
#nullable enable annotations

namespace MyApp.@record
{
    partial class @record<@required>
    {
        private static partial global::Velvet.VNode Build<@scoped>(@scoped x, @required y)
            => global::Velvet.V.Memoized(() => Build_Impl<@scoped>(x, y), new object?[] { x, y, typeof(@scoped) });
    }
}
