// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class RowViews
    {
        public static partial global::Velvet.VNode ToView(this in global::MyApp.Pages.Row row)
        {
            var rowValue = row;
            return global::Velvet.V.Memoized(() => ToView_Impl(rowValue), new object?[] { rowValue });
        }
    }
}
