// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode Build<TItem, TKey, TRow, TCell>(TItem item, TKey key, TRow row, TCell cell)
            where TItem : class?, global::System.IComparable<TItem>, new()
            where TKey : notnull
            where TRow : struct
            where TCell : unmanaged
            => global::Velvet.V.Memoized(() => Build_Impl<TItem, TKey, TRow, TCell>(item, key, row, cell), item, key, row, cell);
    }
}
