// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class HomePage
    {
        public sealed override partial global::Velvet.VNode Header<T>(T title)
            => global::Velvet.V.Memoized(() => Header_Impl<T>(title), new object?[] { title, typeof(T), this });
    }
}
