// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode Build<TValue>(in int T, TValue value)
        {
            var TValue_ = T;
            return global::Velvet.V.Memoized(() => Build_Impl<TValue>(TValue_, value), new object?[] { TValue_, value, typeof(TValue), this });
        }
    }
}
