// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode Build(in global::MyApp.Pages.Row row, string title, in int rowValue)
        {
            var rowValue_ = row;
            var rowValueValue = rowValue;
            return global::Velvet.V.Memoized(() => Build_Impl(rowValue_, title, rowValueValue), rowValue_, title, rowValueValue);
        }
    }
}
