// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode Build(string @class)
            => global::Velvet.V.Memoized(() => Build_Impl(@class), new object?[] { @class });
    }
}
