// <auto-generated/>
#nullable enable annotations

namespace MyApp
{
    partial class Outer
    {
        partial class Inner
        {
            private partial global::Velvet.VNode Build(int x)
                => global::Velvet.V.Memoized(() => Build_Impl(x), x);
        }
    }
}
