// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode Build(string title, params string[] items)
            => global::Velvet.V.Memoized(() => Build_Impl(title, items), title, items);
    }
}
