// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial class HomePage
    {
        private partial global::Velvet.VNode Build(string title, params string[] items)
        {
            var deps = new object?[3 + (items?.Length ?? 0)];
            deps[0] = title;
            deps[1] = this;
            deps[2] = items?.Length;
            if (items != null) global::System.Array.Copy(items, 0, deps, 3, items.Length);
            return global::Velvet.V.Memoized(() => Build_Impl(title, items), deps);
        }
    }
}
