// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial struct RowView
    {
        public readonly partial global::Velvet.VNode Build(int x)
        {
            var self = this;
            return global::Velvet.V.Memoized(() => self.Build_Impl(x), x);
        }
    }
}
