// <auto-generated/>
#nullable disable

namespace MyApp.Pages
{
    partial class StaticHost
    {
        public static partial global::Velvet.VNode Build(int x)
            => global::Velvet.V.Memoized(() => Build_Impl(x), x);
    }
}
