// <auto-generated/>
#nullable enable annotations

namespace MyApp.Pages
{
    partial struct RowView
    {
        public partial global::Velvet.VNode Build(int self, in int row)
        {
            var self_ = this;
            var rowValue = row;
            return global::Velvet.V.Memoized(() => self_.Build_Impl(self, rowValue), new object?[] { self, rowValue });
        }
    }
}
